import torch
from torch import nn
from transformers import AutoModelForImageTextToText, AutoTokenizer
from transformers.dynamic_module_utils import get_class_from_dynamic_module
import numpy as np

class SmolVLAFast(nn.Module):
    """SmolVLA model with FAST action tokens integrated into the vocabulary.
    
    This implementation replaces the least used tokens of the VLM backbone
    with action tokens generated by the FAST action tokenizer.
    """

    def __init__(
        self, 
        model_id: str = "HuggingFaceTB/SmolVLM2-500M-Video-Instruct", 
        num_fast_tokens: int = 1024,
        least_used_tokens: list[int] = None,
        device: str = "cuda" if torch.cuda.is_available() else "cpu",
        torch_dtype = torch.bfloat16
    ) -> None:
        super().__init__()
        self.device = device
        self.num_fast_tokens = num_fast_tokens
        
        # 1. Load VLM and its tokenizer
        self.vlm = AutoModelForImageTextToText.from_pretrained(
            model_id,
            torch_dtype=torch_dtype,
            low_cpu_mem_usage=True,
        ).to(device)
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)
        
        # 2. Load Action Processor (FAST)
        bpe_tokenizer = AutoTokenizer.from_pretrained(
            "physical-intelligence/fast", trust_remote_code=True
        )
        processor_class = get_class_from_dynamic_module(
            "processing_action_tokenizer.UniversalActionProcessor",
            "physical-intelligence/fast",
        )
        self.action_processor = processor_class(bpe_tokenizer=bpe_tokenizer)
        
        # 3. Define Token Replacement Mapping
        if least_used_tokens is None:
            # Fallback: use the last N tokens (excluding some very last ones if they are special)
            # For SmolVLM, let's take tokens from len(vocab) - 1024 - 100 to len(vocab) - 100
            # to avoid overlapping with some potential special tokens at the very end.
            # Ideally, this should be a pre-computed list.
            self.action_token_ids = list(range(len(self.tokenizer) - num_fast_tokens - 100, len(self.tokenizer) - 100))
        else:
            assert len(least_used_tokens) >= num_fast_tokens
            self.action_token_ids = least_used_tokens[:num_fast_tokens]
            
        # Reverse mapping for decoding
        self.vlm_to_action_map = {vlm_id: i for i, vlm_id in enumerate(self.action_token_ids)}
        
        # 4. Re-initialize weights for these tokens
        self._initialize_action_embeddings()

    def _initialize_action_embeddings(self):
        """Re-initialize embeddings and LM head for the repurposed action tokens."""
        embed_tokens = self.vlm.get_input_embeddings()
        lm_head = self.vlm.get_output_embeddings()
        
        with torch.no_grad():
            # Initialize with small random values or zero
            # OpenPI often uses a specific initialization or just fine-tunes.
            # Here we just ensure they are not carrying over old text embedding weights.
            nn.init.normal_(embed_tokens.weight[self.action_token_ids], std=0.02)
            if hasattr(lm_head, 'weight'):
                nn.init.normal_(lm_head.weight[self.action_token_ids], std=0.02)

    def encode_actions(self, actions: np.ndarray) -> torch.Tensor:
        """Convert action chunks to VLM token IDs.
        
        Args:
            actions: numpy array of shape (batch, chunk_size, action_dim)
        Returns:
            torch.Tensor of VLM token IDs (batch, chunk_size)
        """
        # FAST processor returns token IDs in [0, 2047] (or similar)
        fast_tokens = self.action_processor(actions) # returns list of lists or numpy
        fast_tokens = torch.tensor(fast_tokens, device=self.device)
        
        # Clip to num_fast_tokens if necessary, or ensure mapping is large enough
        fast_tokens = torch.clamp(fast_tokens, 0, self.num_fast_tokens - 1)
        
        # Map to VLM token IDs
        # This is a bit slow if done one by one, but for small batches it's okay.
        # Efficient way:
        vlm_token_ids = torch.tensor(self.action_token_ids, device=self.device)[fast_tokens]
        return vlm_token_ids

    def decode_actions(self, vlm_tokens: torch.Tensor) -> np.ndarray:
        """Convert VLM token IDs back to action chunks.
        
        Args:
            vlm_tokens: torch.Tensor of shape (batch, chunk_size)
        Returns:
            numpy array of action chunks
        """
        # Map VLM tokens back to action indices (0-1023)
        vlm_tokens_cpu = vlm_tokens.cpu().numpy()
        # Handle tokens that are NOT in our action map by mapping them to 0 or a special ignore index
        action_tokens = np.vectorize(lambda x: self.vlm_to_action_map.get(x, 0))(vlm_tokens_cpu)
        
        # Decode using action processor
        return self.action_processor.decode(action_tokens)

    def prepare_inputs_for_training(self, batch, camera_keys):
        """Prepare inputs and targets for training.
        
        Args:
            batch: dict containing 'observation.images.*', 'task', and 'action'
            camera_keys: list of camera keys to use
        """
        processor = self.vlm.processor
        batch_size = batch["task"].shape[0] if isinstance(batch["task"], torch.Tensor) else len(batch["task"])
        
        # 1. Process images
        imgs_list = []
        for key in camera_keys:
            imgs = batch[key] # [B, C, H, W]
            imgs_list.extend([imgs[i].cpu() for i in range(batch_size)])
        
        # We assume one image per camera per step for now
        # SmolVLM processor handles multiple images
        inputs = processor(images=imgs_list, text=[""]*batch_size, return_tensors="pt", do_rescale=False)
        pixel_values = inputs["pixel_values"].to(self.device)
        
        # 2. Tokenize tasks
        tasks = batch["task"]
        # Format as: "Task: {task} Action:"
        prompts = [f"Task: {t} Action:" for t in tasks]
        text_inputs = self.tokenizer(prompts, return_tensors="pt", padding=True).to(self.device)
        
        # 3. Encode actions
        actions = batch["action"].cpu().numpy() # [B, T, D]
        action_token_ids = self.encode_actions(actions) # [B, T]
        
        # 4. Concatenate everything for causal modeling
        # This part depends on how SmolVLM structures its input_ids (where image tokens go)
        # Usually, processor(images=..., text=...) handles the <image> token placement.
        
        # For simplicity, let's just return the components and let the training loop handle it
        # or implement the full concat here.
        return {
            "pixel_values": pixel_values,
            "input_ids": text_inputs["input_ids"],
            "attention_mask": text_inputs["attention_mask"],
            "labels": action_token_ids
        }

    def generate_action(self, pixel_values, task, chunk_size=None):
        """Generate action tokens and decode them."""
        if chunk_size is None:
            chunk_size = 50 # Default from FAST
            
        prompt = f"Task: {task} Action:"
        inputs = self.vlm.processor(images=pixel_values, text=prompt, return_tensors="pt").to(self.device)
        
        # Generate
        output_ids = self.vlm.generate(
            **inputs, 
            max_new_tokens=chunk_size,
            do_sample=False, # Usually greedy for actions
            use_cache=True
        )
        
        # Extract new tokens (the actions)
        new_tokens = output_ids[:, inputs["input_ids"].shape[1]:]
        
        # Decode
        return self.decode_actions(new_tokens)
