import torch
from torch import nn
import torch.nn.functional as F
from dataclasses import dataclass
from transformers import AutoTokenizer
from transformers.dynamic_module_utils import get_class_from_dynamic_module
import numpy as np

from lerobot.policies.smolvla import modeling_smolvla
from lerobot.policies.smolvla.configuration_smolvla import SmolVLAConfig
from lerobot.policies.smolvla.processor_smolvla import make_smolvla_pre_post_processors
from lerobot.configs.policies import PreTrainedConfig
from lerobot.utils.constants import (
    OBS_LANGUAGE_ATTENTION_MASK,
    OBS_LANGUAGE_TOKENS,
    ACTION,
)


@PreTrainedConfig.register_subclass("smolvla_fast")
@dataclass
class SmolVLAFastConfig(SmolVLAConfig):
    num_fast_tokens: int = 1024
    model_id: str = "HuggingFaceTB/SmolVLM2-500M-Video-Instruct"
    action_stats: dict[str, np.ndarray] | None = None


class SmolVLAFast(modeling_smolvla.VLAFlowMatching):
    """SmolVLA model with FAST action tokens integrated into the vocabulary.

    This implementation replaces the least used tokens of the VLM backbone
    with action tokens generated by the FAST action tokenizer.
    """

    def __init__(self, config: SmolVLAFastConfig):
        # Set vlm_model_name from model_id if not present
        if not hasattr(config, "vlm_model_name") or config.vlm_model_name is None:
            config.vlm_model_name = config.model_id

        config.compile_model = False
        super().__init__(config)
        self.config = config
        self.action_stats = config.action_stats

        # Load FAST Action Processor
        bpe_tokenizer = AutoTokenizer.from_pretrained(
            "physical-intelligence/fast", trust_remote_code=True
        )
        processor_class = get_class_from_dynamic_module(
            "processing_action_tokenizer.UniversalActionProcessor",
            "physical-intelligence/fast",
        )
        self.action_processor = processor_class(bpe_tokenizer=bpe_tokenizer)
        # Initialize tokenizer by encoding dummy actions to set time_horizon and action_dim for decoding
        dummy_actions = np.zeros((1, config.chunk_size, config.max_action_dim))
        self.action_processor(dummy_actions)

        # Define Token Replacement Mapping
        self.action_token_ids = list(range(48000, 48000 + config.num_fast_tokens))
        self.vlm_to_action_map = {
            vlm_id: i for i, vlm_id in enumerate(self.action_token_ids)
        }

        self._initialize_action_embeddings()

    def _initialize_action_embeddings(self):
        """Re-initialize embeddings and LM head for the repurposed action tokens."""
        embed_tokens = self.vlm_with_expert.vlm.get_input_embeddings()
        lm_head = self.vlm_with_expert.vlm.get_output_embeddings()

        with torch.no_grad():
            nn.init.normal_(embed_tokens.weight[self.action_token_ids], std=0.02)
            if hasattr(lm_head, "weight"):
                nn.init.normal_(lm_head.weight[self.action_token_ids], std=0.02)

    def _normalize_actions(self, actions: np.ndarray) -> np.ndarray:
        """Apply quantile normalization to [-1, 1] if stats are provided."""
        if self.action_stats is None:
            return actions

        q01 = self.action_stats.get("q01", self.action_stats.get("min"))
        q99 = self.action_stats.get("q99", self.action_stats.get("max"))
        # Linear mapping from [q01, q99] to [-1, 1]
        normalized = 2.0 * (actions - q01) / (q99 - q01 + 1e-8) - 1.0
        return normalized

    def _denormalize_actions(self, normalized: np.ndarray) -> np.ndarray:
        """Invert quantile normalization."""
        if self.action_stats is None:
            return normalized

        q01 = self.action_stats.get("q01", self.action_stats.get("min"))
        q99 = self.action_stats.get("q99", self.action_stats.get("max"))
        actions = (normalized + 1.0) / 2.0 * (q99 - q01 + 1e-8) + q01
        return actions

    def encode_actions(
        self, actions: np.ndarray, return_mask: bool = False
    ) -> torch.Tensor:
        """Convert action chunks to VLM token IDs with padding."""
        if actions.ndim == 2:
            actions = np.expand_dims(actions, axis=1)

        # 1. Normalize
        actions = self._normalize_actions(actions)

        # 2. FAST processor returns list of lists of token IDs
        fast_tokens_list = self.action_processor(actions)

        # 3. Padding
        max_len = max(len(t) for t in fast_tokens_list)
        padded_tokens = []
        masks = []
        for t in fast_tokens_list:
            padded = t + [0] * (max_len - len(t))
            mask = [True] * len(t) + [False] * (max_len - len(t))
            padded_tokens.append(padded)
            masks.append(mask)

        device = self.vlm_with_expert.vlm.device
        fast_tokens = torch.tensor(padded_tokens, device=device)

        # 4. Clip and Map to VLM token IDs
        fast_tokens = torch.clamp(fast_tokens, 0, self.config.num_fast_tokens - 1)
        vlm_token_ids = torch.tensor(self.action_token_ids, device=device)[fast_tokens]

        if return_mask:
            return vlm_token_ids, torch.tensor(masks, device=device)
        return vlm_token_ids

    def decode_actions(self, vlm_tokens: torch.Tensor) -> np.ndarray:
        """Convert VLM token IDs back to action chunks."""
        vlm_tokens_cpu = vlm_tokens.cpu().numpy()
        action_tokens = np.vectorize(lambda x: self.vlm_to_action_map.get(x, 0))(
            vlm_tokens_cpu
        )
        normalized_actions = self.action_processor.decode(action_tokens)

        # Denormalize
        return self._denormalize_actions(normalized_actions)

    def _prepare_batch(self, batch: dict[str, torch.Tensor]):
        """Extract and prepare components from the batch."""
        images, img_masks = modeling_smolvla.SmolVLAPolicy.prepare_images(self, batch)
        state = modeling_smolvla.SmolVLAPolicy.prepare_state(self, batch)
        
        # Ensure input tensors match the VLM model's dtype
        dtype = self.vlm_with_expert.vlm.dtype
        images = [img.to(dtype) for img in images]
        state = state.to(dtype)

        lang_tokens = batch[f"{OBS_LANGUAGE_TOKENS}"]
        lang_masks = batch[f"{OBS_LANGUAGE_ATTENTION_MASK}"]
        return images, img_masks, state, lang_tokens, lang_masks

    # pylint: disable=arguments-differ,too-many-locals
    def forward(self, batch: dict[str, torch.Tensor]):
        """Forward pass with AR loss on FAST tokens, including observation state."""
        images, img_masks, state, lang_tokens, lang_masks = self._prepare_batch(batch)

        # 1. Embed prefix (images + language + state)
        prefix_embs, prefix_pad_masks, prefix_att_masks = self.embed_prefix(
            images, img_masks, lang_tokens, lang_masks, state=state
        )

        # 2. Encode and embed actions
        actions = batch[ACTION].cpu().numpy()
        action_token_ids, action_mask = self.encode_actions(actions, return_mask=True)
        action_embs = self.vlm_with_expert.embed_language_tokens(action_token_ids)

        # 3. Combine prefix and actions
        full_embs = torch.cat([prefix_embs, action_embs], dim=1)
        full_pad_masks = torch.cat([prefix_pad_masks, action_mask], dim=1)

        # Actions use causal attention (att_mask = 1)
        action_att_masks = torch.ones(
            (prefix_att_masks.shape[0], action_token_ids.shape[1]),
            dtype=prefix_att_masks.dtype,
            device=prefix_att_masks.device,
        )
        full_att_masks = torch.cat([prefix_att_masks, action_att_masks], dim=1)

        # 4. Prepare masks and position IDs
        full_att_2d_masks = modeling_smolvla.make_att_2d_masks(
            full_pad_masks, full_att_masks
        )
        full_position_ids = torch.cumsum(full_pad_masks, dim=1) - 1

        # 5. VLM Forward
        outputs_embeds, _ = self.vlm_with_expert.forward(
            attention_mask=full_att_2d_masks,
            position_ids=full_position_ids,
            past_key_values=None,
            inputs_embeds=[full_embs, None],
            use_cache=False,
            fill_kv_cache=True,
        )

        vlm_hidden = outputs_embeds[0]
        logits = self.vlm_with_expert.vlm.language_model.lm_head(vlm_hidden)

        # 6. Compute AR Loss
        labels = torch.full_like(full_pad_masks.long(), -100)
        prefix_len = prefix_embs.shape[1]
        action_labels = torch.where(
            action_mask,
            action_token_ids,
            torch.tensor(-100, device=action_token_ids.device),
        )
        labels[:, prefix_len:] = action_labels

        # Shift for AR: predict token at t from hidden state at t-1
        shift_logits = logits[:, prefix_len - 1 : -1, :].contiguous()
        shift_labels = labels[:, prefix_len:].contiguous()

        loss = F.cross_entropy(
            shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1)
        )
        return loss

    def generate_action(self, batch, chunk_size=None):
        """Generate action tokens including observation state."""
        if chunk_size is None:
            chunk_size = self.config.chunk_size

        images, img_masks, state, lang_tokens, lang_masks = self._prepare_batch(batch)

        prefix_embs, prefix_pad_masks, _ = self.embed_prefix(
            images, img_masks, lang_tokens, lang_masks, state=state
        )

        # Compute how many tokens are required for the action chunk of size chunk_size
        dummy = np.zeros((1, chunk_size, self.config.max_action_dim))
        num_new_tokens = len(self.action_processor(dummy)[0])

        output_ids = self.vlm_with_expert.vlm.generate(
            inputs_embeds=prefix_embs,
            attention_mask=prefix_pad_masks,
            max_new_tokens=num_new_tokens,
            do_sample=False,
            use_cache=True,
        )

        return self.decode_actions(output_ids)

    def get_pre_processor(self, dataset):
        pre, _ = make_smolvla_pre_post_processors(
            self.config,
            dataset.meta.stats,
        )
        return pre
